### ISSUE TITLE
Frontend user registration

### ISSUE THREAD

**Issue by sladjan76** [Kunstmaan/KunstmaanBundlesStandardEdition#102]
Hello,
Is there a way to make registration and login for frontend users which will be using frontend layout , but not admin?

**Comment by roderik** [comment]
We'll convert this into a doc item, thx!

**Comment by tentwofour** [comment]
Great! I can share the final working setup if you'd like; this was pretty preliminary, I ended up with a few service overrides for FOSUser, and a helper service to get the nodemenu within the overridden controllers. Shoot me a message if you're interested.

**Comment by roderik** [comment]
That would be great!

**Comment by tentwofour** [comment]
Github-markdown formatted ok? I could add it as a README to whichever 
bundle you'd like, maybe the main BundlesCMS?

On 3/30/2015 11:16 AM, Roderik van der Veer wrote:
>
> That would be great!
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/issues/102#issuecomment-87778367>.
>

-- 

Blair Patterson / Owner/Coder/Geek / TenTwentyFour Interactive / 
http://tentwentyfour.ca

<http://tentwentyfour.ca> <https://twitter.com/1024interactive>

This e-mail message may contain confidential or legally privileged 
information and is intended only for the use of the intended 
recipient(s). Any unauthorized disclosure, dissemination, distribution, 
copying or the taking of any action in reliance on the information 
herein is prohibited. E-mails are not secure and cannot be guaranteed to 
be error free as they can be intercepted, amended, or contain viruses. 
Anyone who communicates with us by e-mail is deemed to have accepted 
these risks. Company Name is not responsible for errors or omissions in 
this message and denies any responsibility for any damage arising from 
the use of e-mail. Any opinion and other statement contained in this 
message and any attachment are solely those of the author and do not 
necessarily represent those of the company.



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by roderik** [comment]
If you open a pull request to https://github.com/roderik/KunstmaanBundlesCMS/tree/master/docs and make the file 05-01-frontend-user-registration.md, i can merge it back with the new documentation pull request

**Comment by tentwofour** [comment]
Sounds good, I'll work on it this week.

On 3/30/2015 11:24 AM, Roderik van der Veer wrote:
>
> If you open a pull request to 
> https://github.com/roderik/KunstmaanBundlesCMS/tree/master/docs and 
> make the file 05-01-frontend-user-registration.md, i can merge it back 
> with the new documentation pull request
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/issues/102#issuecomment-87780186>.
>

-- 

Blair Patterson / Owner/Coder/Geek / TenTwentyFour Interactive / 
http://tentwentyfour.ca

<http://tentwentyfour.ca> <https://twitter.com/1024interactive>

This e-mail message may contain confidential or legally privileged 
information and is intended only for the use of the intended 
recipient(s). Any unauthorized disclosure, dissemination, distribution, 
copying or the taking of any action in reliance on the information 
herein is prohibited. E-mails are not secure and cannot be guaranteed to 
be error free as they can be intercepted, amended, or contain viruses. 
Anyone who communicates with us by e-mail is deemed to have accepted 
these risks. Company Name is not responsible for errors or omissions in 
this message and denies any responsibility for any damage arising from 
the use of e-mail. Any opinion and other statement contained in this 
message and any attachment are solely those of the author and do not 
necessarily represent those of the company.



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com
