### ISSUE TITLE
Make homepage NewsOverviewPage type

### ISSUE THREAD

**Issue by mrcmorales** [Kunstmaan/KunstmaanBundlesStandardEdition#104]
Hello,

I want to make typical blog, I installed kunstmaan Bundle StandarEdition and i have created a news article with kuma:generate:article sf command.

It works but I want that homepage be the list of articles.

How I can change homepage type ?
Thanks

**Comment by bobemoe** [comment]
The best way I have found to do this is to edit your data fixtures, so the home page is initially created as a NewsOverviewPage.

You can find your fixtures file at src/YourBundle/DataFixtures/ORM/DefaultSiteGenerator/DefaultSiteFixtures.php

I dont think its is possable to change a page type once it has been created, not in the admin anyway, you may be able to manually change the type in the database but that's a bit hacky! Someone correct me if I'm wrong here.. this would be useful functionality.
