### ISSUE TITLE
Array to string conversion in 'kunstmaan_taggingbundle_tags' type

### ISSUE THREAD

**Issue by mrcmorales** [Kunstmaan/KunstmaanBundlesStandardEdition#105]
Hi,

I'm using KunstmaanTaggingBundle and I obtained this error:

Notice: Array to string conversion in /vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/ChoiceList/ChoiceList.php line 458

What can i do ?

Thanks

**Comment by jockri** [comment]
Looks like this is solved in the latest version.
