### ISSUE TITLE
estonia and swedish language

### ISSUE THREAD

**Issue by konstantinsp** [Kunstmaan/KunstmaanBundlesStandardEdition#107]
Hello,
I'm making site with estonia and swedish translation.
i noticed that you dont have estonian in your language analyzer
and also you have old swedish country code.

Could you add estonian and new swedish code to language analizer?

for now i've added the manually to this file:
**/../vendor/kunstmaan/bundles-cms/src/Kunstmaan/SearchBundle/Resources/config/analyzer_languages.yml**

    //ADD
    ee: { analyzer: 'estonian' }
    se: { analyzer: 'swedish' }

**Comment by krispypen** [comment]
this was done in https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/77
