### ISSUE TITLE
Update liipimaginebundle

### ISSUE THREAD

**Issue by kimausloos** [Kunstmaan/KunstmaanBundlesStandardEdition#109]
The current version we use is v0.22, we should update.

**Comment by boutitinizar** [comment]
please you can update this  current version liipimaginebundle ?

**Comment by 0xPr0xy** [comment]
please you can update this current version liipimaginebundle to v0.21.1 please?
I want to use the runtime config like:

<code>
{% set runtimeConfig = {"thumbnail": {"size": [50, 50] }} %}
</code>
<code>
< img src="{{ 'path_to_img.jpg' | imagine_filter('my_thumb', runtimeConfig) }}" / >
</code>

**Comment by roderik** [comment]
Moved this to https://github.com/Kunstmaan/KunstmaanBundlesCMS/issues/228
