### ISSUE TITLE
exception following the install instructions (on dev)

### ISSUE THREAD

**Issue by samuele-mrapps** [Kunstmaan/KunstmaanBundlesStandardEdition#110]
After I run this command:
php composer.phar create-project kunstmaan/bundles-standard-edition path/to/install -s dev

I receive the following exception:
An exception occured in driver: SQLSTATE[42000] [1049] Unknown database 'database_name'

At the moment as a workaround I create the database manually (not from app/console) and then I follow the installation instructions starting from app/console schema:create

**Comment by d70rr3s** [comment]
Hi, i run the installation commando with composer and it gives me a lot of dependency ambiguos warning at the end mostly related to alchemy\google-plus-api-client library, also when it finishes raise an exception see below:

![image](https://cloud.githubusercontent.com/assets/5814113/6122456/1a5c713c-b0f4-11e4-96d8-62a7a218f3f7.png)

I'm testing kunstmaan bundles as an architectural base for my projects

**Comment by samuele-mrapps** [comment]
It's not related to this issue. In the KunstmaanBundlesCMS repository is already marked as an issue the alchemy\google-plus-api-client warnings. This project require that you install ImageMagick extension in your web server.
http://www.imagemagick.org/script/binary-releases.php

**Comment by roderik** [comment]
The Imagick dependency is also optional since https://github.com/Kunstmaan/KunstmaanBundlesCMS/commit/631a76168a8d5ddaf32d1bd26a75b322aecc57b1

But I have yet to tag a new version, will try to do so today

**Comment by d70rr3s** [comment]
@samuele-mrapps, sorry for duplicating the issue and misplaced comment.

**Comment by dharmendrajadon** [comment]
After creating database schema, I confused what to do
