### ISSUE TITLE
ckeditor config.js

### ISSUE THREAD

**Issue by bobemoe** [Kunstmaan/KunstmaanBundlesStandardEdition#111]
I want to edit the config.js file to enable config.extraPlugins = 'scayt'; as per the [docs here](https://github.com/Kunstmaan/KunstmaanAdminBundle/tree/master/Resources/public/js/ckeditor/plugins/scayt) but I cant work out which config.js to edit.  

I guess I dont want to be editing the actual source in./vendor/kunstmaan/admin-bundle/Kunstmaan/AdminBundle/Resources/public/js/ckeditor/config.js and I have tried putting one in ./app/Resources/KunstmaanAdminBundle/public/js/ckeditor/config.js but it seems to be ignored. 

What is the best way to edit this file? Thanks.

**Comment by borisklotz** [comment]
The following worked fine for me (Kunstmaan Bundles Version 3.0):
1. Copy the file ckeditor.js.twig from vendor/kunstmaan/bundles-cms/src/Kunstmaan/AndminBundle/Resources/views/Default/ckeditor.js.twig to app/Resources/KunstmaanAdminBundle/views/Default/ckeditor.js.twig
2. Make your adaptions to the

**Comment by roderik** [comment]
I believe this has been handles a while back? If this is still an issue in the latest version, please add an issue at https://github.com/Kunstmaan/KunstmaanBundlesCMS
