### ISSUE TITLE
Brand new installation - bourbon

### ISSUE THREAD

**Issue by Warxcell** [Kunstmaan/KunstmaanBundlesStandardEdition#112]
This is a fresh brand new installation of kunstmaan thru http://bundles.kunstmaan.be/getting-started/installation
Some of generated SCSS paths are wrong.

`node_modules/grunt-cli/bin/grunt build
Syntax error: File to import not found or unreadable: ../../../../../../../web/vendor/bourbon/app/assets/stylesheets/_bourbon.`

File exists but with extension:

`web/vendor/bourbon/app/assets/stylesheets/_bourbon.scss`

**Comment by roderik** [comment]
If this is still an issue in the latest version, please add an issue at https://github.com/Kunstmaan/KunstmaanBundlesCMS
