### ISSUE TITLE
CSS doesn't load properly

### ISSUE THREAD

**Issue by Philippe-Mange** [Kunstmaan/KunstmaanBundlesStandardEdition#113]
Hi Kunstmaan 

I just installed the bundles. 
When i open the website ... the stylesheet in the frontend gives me an 503 Service Unavailable
on the admin pages i have some more info in the CSS
/*
[exception] 500 | Internal Server Error | Assetic\Exception\FilterException
[message] An error occurred while running:
'/usr/bin/ruby' '/usr/local/bin/sass' '--load-path' '/home/philippe/websites/cmf/vendor/kunstmaan/bundles-cms/src/Kunstmaan/AdminBundle/Resources/public/scss' '--scss' '--load-path' '/home/philippe/websites/cmf/app/../web' '--cache-location' '/tmp' '/tmp/assetic_sassLdWr4f'
Error Output:
Errno::ENOENT: No such file or directory - /tmp/600d657f6ac2358f30ba6bc0ab4cd7ffb6194ced/assetic_sassLdWr4fc20150123-4823-toodux.lock
Use --trace for backtrace. 

I have no idea where to start looking ! 
thx in advance for any tips

**Comment by roderik** [comment]
If this is still an issue in the latest version, please add an issue at https://github.com/Kunstmaan/KunstmaanBundlesCMS

**Comment by wrossier** [comment]
Hi, Did you follow all config ? Dis you install :npm install -g bower
npm install -g gulp
npm install -g uglify-js
npm install -g uglifycss
gem install bundler

I got this problem and i solved it
