### ISSUE TITLE
Class SymfonyStandard\Composer is not autoloadable, can not call post-root-package-install script

### ISSUE THREAD

**Issue by samuele-mrapps** [Kunstmaan/KunstmaanBundlesStandardEdition#114]
When I launch this command:
php composer.phar create-project kunstmaan/bundles-standard-edition path/to/install
I get this warning:
Class SymfonyStandard\Composer is not autoloadable, can not call post-root-package-install script
So seems that composer can't execute a post install script because it doesn't find the class.

**Comment by oacevedo** [comment]
I have the same problem... :(

**Comment by roderik** [comment]
Fixed in the latest release!
