### ISSUE TITLE
STUCK: PHP Fatal error:  Class 'Imagick' not found in ... cache/dev/appDevDebugProjectContainer.php on line 3573

### ISSUE THREAD

**Issue by beyondthestatic** [Kunstmaan/KunstmaanBundlesStandardEdition#117]
Hey Guys,

just found your very good looking Symfony Bundles and tried to install it in OSX.

Everything worked but at the end of console parameter inputs i got stuck.

''' [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command.  '''

After that every console command referenced to this missing class.

''' php app/console kuma:generate:bundle
PHP Fatal error:  Class 'Imagick' not found in ... /app/cache/dev/appDevDebugProjectContainer.php on line 3573 '''

Looks like i need ImageMagick? 
But i did not find it in your install instructions?

Am i missing something?

Cheers, *m

**Comment by Philippe-Mange** [comment]
Hi 

Try to install IMAGICK on your OSX 
Maybe this link will help: https://github.com/delphian/drupal-convert-file/wiki/Installing-ImageMagick-on-Mac-OSX-for-PHP-and-MAMP

**Comment by beyondthestatic** [comment]
Hi Phillip, THX for the Tipp.

But is there any step in the installation process that says ImageMagick is mandatory? 
Did i miss something?

**Comment by denbatte** [comment]
Hi,

The getting started says. imagick needs to be enabled (if you wish to use the KunstmaanMediaBundle). The mediabundle is required in the cms bundle.

**Comment by beyondthestatic** [comment]
Now i see it sorry, THX for the support guys!
