### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by sooron** [Kunstmaan/KunstmaanBundlesStandardEdition#122]
Hi,
There are a bunch of installation problems i ran into following the installation guide.

About installing node, I had to use this command instead (on Ubuntu) :
apt-get install nodejs nodejs-legacy npm

There's another package missing it seems to be able to build grunt without errors :
npm install -g imagemin-gifsicle

The path of the node executable is wrong in the app/config/config_dev.yml fil, but OK in the app/config/config.yml (should be /usr/bin/node, and not usr/local/bin/node).

Last thing i didn't manage to fix yet, is that pictures don't load on the demo site. Is there any idea why is it not loading ? I've read about this type of thing of Symfony2 happenging, and a work-around to fix it, but it doesn't seem to apply with KBSE (the /sf alias).

**Comment by denbatte** [comment]
Hi Sooron,

In the Ubuntu repositories, there seems to be a other package called node.
The best way is to remove the other node package and install nodejs.
You should indeed be able to install with: apt-get install nodejs.
Once nodejs is installed you could also make a symlink in the bin folder from node to nodejs.

About the node path, this just depends on how you (and your system) installed node.
A easy way to find the right path is: whereis nodejs or whereis node

I'm planning to make a blog post about how to set up a new ubuntu server and have the bundles running on it.
