### ISSUE TITLE
Template modifications Issue

### ISSUE THREAD

**Issue by CGX971** [Kunstmaan/KunstmaanBundlesStandardEdition#123]
Hi,

When I edit a template file, for example :(src/ProjectSandbox/WebsiteBundle/Resources/views/Pages/HomePage/pagetemplate.html.twig).
I can't see any change on the frontend at all.
I already try to clear the cache with: app/console cache:clear.
How can i make it works?

Thx

**Comment by denbatte** [comment]
Hi,
If you didn't modify the default generated routes, try view/Layout/layout.html.twig.

Bart
