### ISSUE TITLE
config_prod should have a single lang version

### ISSUE THREAD

**Issue by kimausloos** [Kunstmaan/KunstmaanBundlesStandardEdition#125]
Currently the fos_http_cache rules in config_prod ( https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/master/app/config/config_prod.yml#L37 ) are made for multilanguage sites only. When you have a single language site, admin gets public headers.

**Comment by roderik** [comment]
Will be handled when we add the MultiDomainBundle
