### ISSUE TITLE
Bower.json is missing

### ISSUE THREAD

**Issue by xtrasmal** [Kunstmaan/KunstmaanBundlesStandardEdition#128]
Hi there,

During the installation I get a lot of errors. 
First thing that happens is that I can not do a ```bower install```  because there isn't a bower.json after doing a ```composer create-project kunstmaan/bundles-standard-edition```

So now there are a lot of assets missing. What to do and how to solve this? 
Do I need to download some extra files from somewhere? Is there a hidden download somewhere that is not described in the manual?

Best regards.

**Comment by roderik** [comment]
The bower.son file is generated via generators in step 4 of the getting started guide: http://bundles.kunstmaan.be/getting-started/installation
