### ISSUE TITLE
"deleted = 0" where expressions gives error with Postgres

### ISSUE THREAD

**Issue by imanzuk** [Kunstmaan/KunstmaanBundlesStandardEdition#130]
Just found that "deleted = 0" where expressions gives "operator does not exist: boolean = integer" error with Postgres when running doctrine:fixtures:load. I am going to investigate and fix it with a pull request.

See #98

**Comment by krispypen** [comment]
At the moment we do not support postgresql, We already test it, see the allowed failures on https://travis-ci.org/Kunstmaan/KunstmaanBundlesStandardEdition , but it would be nice of you can send a PR for it? :)

**Comment by roderik** [comment]
If this is still an issue in the latest version, please add an issue/pull request at https://github.com/Kunstmaan/KunstmaanBundlesCMS
