### ISSUE TITLE
Deprecated the service method in Pages

### ISSUE THREAD

**Issue by thomasverleye** [Kunstmaan/KunstmaanBundlesStandardEdition#142]
I've been trying to work my head around the solution been mentioned on your Upgrade notes of 3.1.
I don't fully understand the part where the Service method is deprecated and needs to move to the controller. What do you guys mean with implementing the SlugActionInterface?

Would be helpfull if there where screenshots added from the before and after process.

**Comment by denbatte** [comment]
Hi @thomasverleye,

In the past, you could use the service() method in your entity to pass things to your template.
This wasn't a good solution so we decided to deprecate it.

So, what you should do is:
- implement the SlugActionInterface at your entity and add the following method in that class
```php
class MyEntity implements SlugActionInterface
{
    // This method should be added in your enity, adjust the return value to represent the controller to use
    public function getControllerAction()
    {
	return 'Bundle:MyCustom:service';
    }
}
```

- create a custom controller for your entity that needs the following method.
```php
class MyCustomController extends Controller
{
    public function serviceAction(Request $request)
    {
	..logic..
	$context['variable'] = $variable;

	$request->attributes->set('_renderContext',$context);
    }
}
```
Hope this clears things up.

**Comment by thomasverleye** [comment]
Thanks for the quick answer, It's now giving me some error:

 Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 2 passed to Kunstmaan\PagePartBundle\Twig\Extension\PageTemplateTwigExtension::renderPageTemplate() must be an instance of Kunstmaan\PagePartBundle\Helper\HasPageTemplateInterface, instance of Superrb\TradeTemplateBundle\Entity\Pages\AboutPage given, called in /Users/thomasverleye/Sites/superrbtemplate/app/cache/dev/twig/1a/5e/85f4cb3bd3329fcb9bfc2756bec580322c43480061f008ab01e751808587.php on line 33 and defined") in SuperrbTradeTemplateBundle:Pages:AboutPage/view.html.twig at line 4.

**Comment by woutervandamme** [comment]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/316, here is a pull request where we changed the old service method to the new implementation. Maybe you can get some inspiration from there.

**Comment by thomasverleye** [comment]
@woutervandamme Thanks! Fixed the problem as I removed the implementation in my entity class of HasPageTemplateInterface and replaced it with SlugActionInterface. But as in your example the entity class needed both of them.

Dankjewel  @woutervandamme en @denbatte voor jullie snelle hulp!
