### ISSUE TITLE
Formpage creation problem

### ISSUE THREAD

**Issue by MarioZ2002** [Kunstmaan/KunstmaanBundlesStandardEdition#153]
When i create a Formpage, the form is not getting passed to the view.

I get this exception :

```Key "formwidget_KunstmaanFormBundleEntityPagePartsSingleLineTextPagePart1" in object with ArrayAccess of class "Symfony\Component\Form\FormView" does not exist in KunstmaanFormBundle:SingleLineTextPagePart:view.html.twig at line 2 ```

I also posted a question on stackoverflow: 
http://stackoverflow.com/questions/30908490/kunstmaan-cms-form-not-getting-passed-to-view

Maybe someone can help.

**Comment by denbatte** [comment]
Hi,

does your entity extends AbstractFormPage and does it implement HasPageTemplateInterface?
It kind of hard to say whats going on without some code error messages or code samples.

**Comment by roderik** [comment]
If this is still an issue in the latest version, please add an issue at https://github.com/Kunstmaan/KunstmaanBundlesCMS
