### ISSUE TITLE
Homepage Exception forwards to /en/

### ISSUE THREAD

**Issue by bobemoe** [Kunstmaan/KunstmaanBundlesStandardEdition#156]
We are running a single language site.  We are currently developing the home page template, and  any exception thrown here is caught somewhere and triggers a 301 to the /en/ page that then 404s.  This is especially annoying as the exception message is not exposed and makes debugging very hard.  

Where can this auto forward be disabled?

Cheers :)

**Comment by laymain** [comment]
You should follow the "Single language websites" section of the documentation
https://bundles.kunstmaan.be/documentation/cookbook/single-language-websites

**Comment by denbatte** [comment]
Can you see the cause of this behaviour in the Symfony error log? 
Maybe even your apache/nginx logs?

**Comment by bobemoe** [comment]
Hey thanks guys :) Although I had followed then single language guide I though I'd double check, and sure enough I'd missed step 5.  Issue now solved :D
