### ISSUE TITLE
Unable to install. DoctrineMigrationsBundle not found.

### ISSUE THREAD

**Issue by ByScripts** [Kunstmaan/KunstmaanBundlesStandardEdition#161]
I'm unable to install Kunstmaan Bundles:

    Your requirements could not be resolved to an installable set of packages.

    Problem 1
    - The requested package doctrine/doctrine-migrations-bundle could not be found in any version, there may be a typo in the package name.

I checked composer.json, it required `doctrine/doctrine-migrations-bundle` at version `2.1.*@dev` ... but [there is no 2.1.* release](https://github.com/doctrine/DoctrineMigrationsBundle/tags) (there is no 2.* release at all)

**Comment by roderik** [comment]
Weird, went back to the last available version: https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/commit/8e68677e75e78704aba2927eda855ad8a1224697 

Not sure wat the repercussions will be

**Comment by krispypen** [comment]
I think something strange is happening on that repo https://github.com/doctrine/DoctrineMigrationsBundle/issues/125
