### ISSUE TITLE
404 Pages

### ISSUE THREAD

**Issue by lewisvgd** [Kunstmaan/KunstmaanBundlesStandardEdition#165]
I'm not sure if this is an issue or im missing a trick but 404s result in a big old exception.

Is there a designed way within Kunstmaan to handle this? (if so, documentation would be helpful)

**Comment by denbatte** [comment]
Hi,

We had an issue with our 404 pages. It should be fixed when you update to the latest version of the bundles. Please let us know otherwise.

**Comment by lewisvgd** [comment]
Groovy, thanks! Looks like it works however, /admin/{anyrandomstringhere} results in the same 404.

Any ideas?

**Comment by denbatte** [comment]
Would you be able to provide a bit more context and information?
Do you have a multilingual site? What exactly did you make (e.g. Adminlist, Page, ...)? Did you create the routes needed?

**Comment by lewisvgd** [comment]
Hi Denbatte,

This is a single language site, it's complete and functional however i'm getting a number of Exception alerts as people try to dig around in the internals.

For example, i'm getting someone trying to access `/admin/fckeditor/editor/filemanager/browser/default/connectors/aspx/connector.aspx?Command=FileUpload&Type=File&CurrentFolder=%2F `

which doesn't exist. Rather than providing them with my lovely 404 page, i'm getting an uncaught ResourceNotFoundException.

If i go to the same URL, but remove the /admin/ prefix:

`/fckeditor/editor/filemanager/browser/default/connectors/aspx/connector.aspx?Command=FileUpload&Type=File&CurrentFolder=%2F `

The 404 page is displayed as desired.

**Comment by lewisvgd** [comment]
Great Thanks
