### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by ngreen30** [Kunstmaan/KunstmaanBundlesStandardEdition#166]
I'm considering using this CMS for a project, however I am struggling to get this running in a dev environment as per the documentation [here](https://bundles.kunstmaan.be/documentation/installation)

When running `composer create-project kunstmaan/bundles-standard-edition myprojectname`, I cant seem to get past the following:

![image](https://cloud.githubusercontent.com/assets/5489064/9735480/0979e63a-5633-11e5-8761-791ecf78f1b0.png)

I have tried this on a few different platforms, including [your vagrant box](https://github.com/Kunstmaan/puphpet). I have also tried editing the composer.json file to pull in lower versions of 'kunstmaan/bundles-cms', but have the same issue. I have also tried running the create-project command with sudo - same issue.

Is this an issue with the current state of the repo, or is there something I can do to work around this?

Any advice would be hugely appreciated.

**Comment by roderik** [comment]
You are having a permission error on your computer. Try the command in a different location

**Comment by ngreen30** [comment]
Thanks for your reply.

That's also what I thought on first glance, however I am running the site in a vagrant box, with Apache & PHP cli both running as the 'vagrant' user. The document root is owned by 'vagrant' _recursively_. The SSH connection I am using is (naturally) the 'vagrant' user account. 

All other packages which the `composer create-project kunstmaan/bundles-standard-edition myprojectname` command installs (jms, doctrine, symfony, sensio etc etc), install successfully - its just when it gets to the 'kunstmaan/bundles-cms' package that it falls over with this error.

As mentioned, I also tried (as a last resort) running the composer commands using sudo - same issue.

Regardless - I tried running the command in a different location as you suggested (this time not owned by vagrant) and immediately get '[ErrorException] mkdir(): Permission denied'.

If this really _is_ a permissions issue - it isn't like any I have seen before.

So no joy yet. Any other ideas please?

**Comment by ngreen30** [comment]
Turns out that this was caused by default vagrant (virtualbox) filesharing on windows. I'm not sure of the exact cause, I just know that when I configure vagrant to use the rsync filesharing method, I no longer have this error.

Thanks for looking!

**Comment by roderik** [comment]
Glad you found it because i had no idea :)
