### ISSUE TITLE
Error running kuma:generate:page command

### ISSUE THREAD

**Issue by onalekitso** [Kunstmaan/KunstmaanBundlesStandardEdition#167]
Urgent help needed

Im getting the below error when trying to run app/console kuma:generate:page

[Symfony\Component\Debug\Exception\ContextErrorException] 
  Notice: Undefined index: rows  

I'm using psr-4 and "kunstmaan/bundles-cms": "~3.0",

**Comment by wimvds** [comment]
You probably defined a pagetemplate without any rows (/regions) in it. So check the pagetemplates you defined. If you find any without rows, just add ```rows: []```.

**Comment by onalekitso** [comment]
Thank you very much.

Highly appreciated

**Comment by wimvds** [comment]
No problem. Glad it helped.
