### ISSUE TITLE
Imagick not installed

### ISSUE THREAD

**Issue by onalekitso** [Kunstmaan/KunstmaanBundlesStandardEdition#168]
Please help

After Mac OS X upgrade to El Capitan I have an Imagick (Imagick not installed) error but my php info should it has been installed and enabled. I have also check the extension using

if (!extension_loaded('imagick'))
    echo 'imagick not installed';
else
    echo 'Installed';

Please find the attached files.

![screen shot 2015-10-04 at 11 49 58 pm](https://cloud.githubusercontent.com/assets/6186801/10276266/ac5aae2c-6b4e-11e5-91ce-be98ecace0e8.png)
![screen shot 2015-10-04 at 11 50 02 pm](https://cloud.githubusercontent.com/assets/6186801/10276265/ac5a8992-6b4e-11e5-817e-0986ecf2284f.png)

**Comment by krispypen** [comment]
Are you doing the phpinfo with the same php.ini file? Maybe the first screenshot comes from apache and the second screenshot from "app/console server:run" ?

Otherwise it's really strange, and maybe post your question in the imagine repo?

**Comment by onalekitso** [comment]
Thank you for the suggestion, i will check  imagine repo
