### ISSUE TITLE
404 Errors - /admin/ prefix

### ISSUE THREAD

**Issue by lewisvgd** [Kunstmaan/KunstmaanBundlesStandardEdition#169]
The 404 error page doesn't work when it's prefixed by a /admin

For example, when trying to access `/admin/fckeditor/editor/filemanager/browser/default/connectors/aspx/connector.aspx?Command=FileUpload&Type=File&CurrentFolder=%2F`

You'll likely get an ResourceNotFoundException rather than providing a lovely 404 page.

If i go to the same URL, but remove the /admin/ prefix:

`/fckeditor/editor/filemanager/browser/default/connectors/aspx/connector.aspx?Command=FileUpload&Type=File&CurrentFolder=%2F`

The 404 page is displayed as desired.

**Comment by wimvds** [comment]
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 169

**Comment by denbatte** [comment]
https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/746
