### ISSUE TITLE
TaggingBundle bug : createdAt and updatedAt

### ISSUE THREAD

**Issue by kamel-allab** [Kunstmaan/KunstmaanBundlesStandardEdition#176]
Hello,
I found a bug in 
Kunstmaan\TaggingBundle\AdminList\TagAdminListConfigurator.php lines : 31 and 32

The field names createdat updatedat have to be the same that in Tag Entity class
protected $createdAt;
protected $updatedAt;

So to fix the bug we should change :
$this->addField('createdat', 'Created at', true);
 $this->addField('updatedat', 'Updated at', true);
To :
 $this->addField('createdAt', 'Created at', true);
 $this->addField('updatedAt', 'Updated at', true);

Best regards,

Kamel ALLAB

**Comment by jockri** [comment]
Hi @kamel-allab, thanks for spotting.
Can you create a PR to fix this issue? 
Thanks!
