### ISSUE TITLE
kuma:user:create / Warning: max(): Array must contain at least one element

### ISSUE THREAD

**Issue by atlance** [Kunstmaan/KunstmaanBundlesStandardEdition#178]
[![asciicast](https://asciinema.org/a/2dywexnxmepywmzyh6vvk9wtr.png)](https://asciinema.org/a/2dywexnxmepywmzyh6vvk9wtr)

**Comment by jockri** [comment]
Hi @atlance!

Can you move this issue to the https://github.com/Kunstmaan/KunstmaanBundlesCMS repository?
Perhaps you can debug a little bit further and send us a PR with the fix?

Thanks!
