### ISSUE TITLE
Installation with composer fails

### ISSUE THREAD

**Issue by floriansemm** [Kunstmaan/KunstmaanBundlesStandardEdition#186]
If I run `composer create-project kunstmaan/bundles-standard-edition destination` then I get at the end `You have requested a non-existent service "fos_user.doctrine_registry"`.

FOSUserBundle is present and it is registered in the AppKernel.

Any idea?

**Comment by sandergo90** [comment]
Hi,

There is already an issue on https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2048.

You could try adding "friendsofsymfony/user-bundle": "~2.0@dev" to your composer.json.

Sander

**Comment by floriansemm** [comment]
Thanks for this! `~2.0@dev` does not work either. With `"friendsofsymfony/user-bundle": "dev-master##6ccff96434c0ac7fee077d1dce90966341dfd278"` the error is gone. I hope everything is working!

**Comment by stof** [comment]
Update to the dev version of Symfony, until Symfony 3.0.2, 2.8.3, 2.7.10 and 2.3.38 are released with the bugfix for the bug affecting FOSUserBundle dev-master
