### ISSUE TITLE
Disabling Search configuration and bundle does not disable usage of ElasticSearch

### ISSUE THREAD

**Issue by Caroga** [Kunstmaan/KunstmaanBundlesStandardEdition#200]
Hi,

I am wishing to disable ElasticSearch. I tried disabling the SearchBundle, as I also removed the `parameters.yml` search configuration. 
Another agreeable solution would being able to define the elasticsearch host ?

Reason to remove this is to eliminate the errors I receive when publishing a page. I have no desire to use elasticsearch functionality in my current project, but being able to set the host for it for another project would be very nice.

**Comment by Caroga** [comment]
Just a quick update, I went through your bundle and found a way to configure the hostname parameter. 
I added the following to my `parameters.yml`:
`kunstmaan_search.hostname: '172.17.0.1'`
This works so far. Would have been nice if there was some documentation where this could be documented in.
Also, it lacks the possibility to disable the ElasticSearch index entirely, this way you do force people to use ES even if there is no need and/or resources to be able to. You might want to reconsider this strategy.

**Comment by ismaserrano** [comment]
Hey @Caroga, is there any possibility to use another simple search engine, without external engine, only Symfony? Your solution does not work for me :(

**Comment by Caroga** [comment]
Unfortunately I've stopped using this software. Therefore my knowledge is not up-to-date to assist you with this, and I recommend you open a new issue (if you have not done this yet). 
Please direct (tag) your question directly to someone of the Kunstmaan dev team as this might improve response time. 
As you might have noticed: they don't take responding to open issues very seriously.
Good luck!

**Comment by Devolicious** [comment]
@Caroga, I'm sorry that your issue got lost in space somehow but that doesn't mean that we don't take answering our issue serious. There are lot's of happy users and we try as much as possible to help out.

@ismaserrano, if you just want to turn of the usage of elasticsearch, you have to disable the `SearchBundle` and the `NodeSearchBundle`. If you're looking for something else, please open a new issue and explain a bit further. 
Hope this helps.
