### ISSUE TITLE
Any community suport?

### ISSUE THREAD

**Issue by PanzerLlama** [Kunstmaan/KunstmaanBundlesStandardEdition#201]
Hi,

After many hours I managed to install the Kunstmaan demo site in single language mode (I had most problems with getting Ruby stuff to work - I never used ruby before) but I have now stopper issues with the locale configuration :/ Any place where I can turn for help?

I setup the default language to pl yet everything is in en and I cannot figure out what to do to activate the pl locale (all is set to pl in the configs).

Translating any texts in Settings ? Translations has no effect, somehow it seems whatever I try Symfony uses en locale. Additionally I get this:

Notice: Undefined index: pl, 500 Internal Server Error - ContextErrorException in vendor/kunstmaan/bundles-cms/src/Kunstmaan/NodeSearchBundle/Configuration/NodePagesConfiguration.php at line 463

when I save any page. :/

Also the home page "/" of the site on my dev server gets infinite redirects to itself.

I would like to get rid of the locale notice above and be able to set the locale to pl.

Any tips appreciated. Thanks.

Panzer Llama

**Comment by Caroga** [comment]
Hi Panzer, 

I've been struggling with the single language installation problem as well. I figured that changing to single language after already generating a website bundle is also very problematic.
I'm currently trying to do so with a new installation where I generate the bundle after changing the security and routing files.
Also please take notice that the JMS security configuration inside the single language security file is causing problems to run the system at all. 
I resolved this by removing the following code:
```
jms_security_extra:
    secure_all_services: false
    expressions: true
```

Also, the UserInterface encoding setting is causing problems as well, the declaration is used by a quoted selector, which is not working.
Changing the following line to be without quotes resolved the fixtures loading:
```
        FOS\UserBundle\Model\UserInterface: sha512
```

Last, but not least, for me the error with saving the pages is for the lack of ElasticSearch. You cannot use it without ElasticSearch, but you can configure it as described here: https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/issues/200


For the language not being able to change: do you see the PL entry inside your language table on the backend?
