### ISSUE TITLE
Edition v3.5.1 requires bundles@dev-master

### ISSUE THREAD

**Issue by ro0NL** [Kunstmaan/KunstmaanBundlesStandardEdition#202]
Is this intended?
https://github.com/Kunstmaan/KunstmaanBundlesStandardEdition/blob/3.5.1/composer.json#L11

I.e. _MUST_ we rely on `kunstmaan/bundles-cms@dev-master` if we want to use `kunstmaan/bundles-standard-edition@3.5.1` or _SHOULD_ we rely on `kunstmaan/bundles-cms@3.5.1` and is composer.json wrongly committed in edition@3.5.1?

**Comment by jockri** [comment]
It is not correct indeed. We should rely on a stable version...
Will be fixed when 3.5.2 is released...
