### ISSUE TITLE
Storing images from media bundle in Amazon S3 and loading with the can?

### ISSUE THREAD

**Issue by w3q** [Kunstmaan/KunstmaanBundlesStandardEdition#204]
Hello, is it possible to configure media manager to store the images to the Amazon S3 storage and then load them through the CDN provider?

Thank you,
Michal

**Comment by jockri** [comment]
Yes this is possible. Take a look at the documentation: https://github.com/Kunstmaan/KunstmaanBundlesCMS/blob/master/docs/05-12-using-a-custom-filesystem-for-the-media-bundle.md

**Comment by iknowfoobar** [comment]
Hi @jockri I have tried to follow that documentation but I can't get it to work. I don't get any errors and the behaviour of the media bundle doesn't change. 

Are there any steps that I should have taken that aren't in that documentation? I had to install the AWS SDK which wasn't in the docs. https://github.com/aws/aws-sdk-php-symfony

I am using KunsmaanBundles 3.5

Thanks
Giles

**Comment by iknowfoobar** [comment]
I have made some progress, If I manually move the files to the uploads bucket then everything starts working fine. E.g. liip_imagine creates the cached versions in the cache bucket and serves them fine. 

It appears that images are not being uploaded to the uploads bucket, but are being put into the file system as normal. I can see in the database that they are marked as local.

Is this a permissions problem potentially, I get no errors when uploading files.

**Comment by jockri** [comment]
@wesleylancel is using S3 for a project in production. Wesley, did you also have problems to move the uploads to S3?

**Comment by iknowfoobar** [comment]
@jockri @wesleylancel I just started all over again on a fresh install of the bundles and it has worked fine this time! 
The only difference is I was previously working on a site that had been upgraded to 3.5 from an earlier version of the bundles. Not sure what the difference is, but is working now.

Thanks for your time.
