### ISSUE TITLE
Use KunstmannBundle in a symfo,y project

### ISSUE THREAD

**Issue by speeeeeed2006** [Kunstmaan/KunstmaanBundlesStandardEdition#206]
Hello, 
Maybe my question is kind of stupid or look easy. I want to know is it possible to use this project or some part of it in a existing symfony project 2.8.4? I was looking for a content management system just like simpleCmsBundle easy to use. My objectif is to use it to manage some page like the home page but I have a part of my website, the subscriber section, managed by fosuserBundle.

**Comment by jockri** [comment]
Yes, this is possible. It depends on the project size whether it is easier to create a new KunstmaanBundlesCMS and then add your own code, or the other way around.

**Comment by speeeeeed2006** [comment]
Thank you for the reply. 
It will be difficult I think to add my code in the KunstmaanBundlesCMS because there's a lot of config to add and but I will give a try to see the difference in performance. Is there a best way to add thebundle in a existing project?

**Comment by jockri** [comment]
Take a look at the configuration of this standard edition (app/config/*, composer.json, app/AppKernel.php, ...), and port it to your own application.

**Comment by speeeeeed2006** [comment]
ok thanks
