### ISSUE TITLE
Multi domain sites with custom templates

### ISSUE THREAD

**Issue by fahadonline** [Kunstmaan/KunstmaanBundlesStandardEdition#215]
Need advice 
Have to develop multiple sites, with custom theme but same content in different languages.
Each site can contain multiple posts, articles or pages etc (content pages in different hierarchy)
Single post, article or page can be on multiple sites.

The issue is that instead of creating separate content pages for each post, article or page on each site,
the user desires to create a single post, article or page in their receptive section 
and simply specify the domains it should be shown.

Apart from that he also desires to specify SEO and permission etc (the options available on page creation)
while creating post, article or page

Any suggestions how to go about building such a system ?

**Comment by Devolicious** [comment]
@fahadonline We have our MultiDomainBundle for this.
