### ISSUE TITLE
how to change language on kunstmaan cms

### ISSUE THREAD

**Issue by taalayuulu** [Kunstmaan/KunstmaanBundlesStandardEdition#221]
Hi there !
I want to change kunstmaan bundle language. I have created single language web page but all admin section completely in english , so may I choose another language as a default , say russian ? If yes , have can I do that and where I can find translations for that ?

**Comment by sandergo90** [comment]
Hi,

In your config.yml you can specify the admin locales:

kunstmaan_admin:
    admin_locales: ['nl', 'en']

You will have to add the translation files for russian because this language currently does not exist in the bundles. You can create a pull request for this of course ;)

Sander

**Comment by taalayuulu** [comment]
thanks dude !
