### ISSUE TITLE
kunstmaan/generatorbundle creates adminlist routing prefix in routing.yml, only works in annotation

### ISSUE THREAD

**Issue by jochendaum** [Kunstmaan/KunstmaanBundlesStandardEdition#226]
Hi,

I'm not using the whole Standard Edition install, instead I just installed required bundles with this composer configuration:

"require": {
        "php": ">=7.0.0",
        "symfony/symfony": "~2.8",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.7",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/finder": "@dev",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "kunstmaan/admin-bundle": "@dev",
        "kunstmaan/adminlist-bundle": "@dev",
        "kunstmaan/generator-bundle": "^3.5"
    }

I created an adminlist with the generatorbundle, but found that the prefix doesn't work. After some research  found that the prefix has to be created in the controller annotation, presumably because you can't mix yml and annotation routing? My app has no other routes so far apart from the homepage route of my bundle - before using the adminlist I have only used cli commands.

The issue is described in more detail here: http://stackoverflow.com/a/40536731/123594

Please let me know if this is by design or I am doing something else wrong

**Comment by jochendaum** [comment]
Also happy to look at fixing this, but a quick squiz in generatorbundle didn't surface anything

**Comment by Devolicious** [comment]
Hi @jochendaum,

That is strange because routing prefixes from the yml definition should work with annotation routes. But I saw on stackoverflow that you've already solved your problem so I'm gonna close this issue.
