### ISSUE TITLE
Issue during installation

### ISSUE THREAD

**Issue by TUBbrain** [Kunstmaan/KunstmaanBundlesStandardEdition#237]
Hi all,

When I try to install bundle following your tutorial at https://bundles.kunstmaan.be/documentation/master/installation

Everything goes well, but something wrong happens when I arrived to the command line : 
bin/console doctrine:fixtures:load

and tells me : 
-bash-4.1$ bin/console doctrine:fixtures:load
Careful, database will be purged. Do you want to continue y/N ? y
  > purging database
  > loading [1] Kunstmaan\GeneratorBundle\DataFixtures\ORM\RoleFixtures
  > loading [1] Kunstmaan\MediaBundle\DataFixtures\ORM\FolderFixtures
  > loading [1] Kunstmaan\TranslatorBundle\DataFixtures\ORM\TranslationFixtures
  > loading [2] Kunstmaan\GeneratorBundle\DataFixtures\ORM\GroupFixtures
  > loading [3] Kunstmaan\GeneratorBundle\DataFixtures\ORM\UserFixtures
  > User 'admin' created with password '*************'
  > loading [51] Client\MairieBundle\DataFixtures\ORM\DefaultSiteGenerator\DefaultSiteFixtures
PHP Fatal error:  Call to a member function transliterate() on a non-object in /home/sites/site199/myprojectname/vendor/kunstmaan/bundles-cms/src/Kunstmaan/UtilitiesBundle/Helper/Slugifier.php on line 29

What must I do now ?

regards,

**Comment by sandergo90** [comment]
Hi @TUBbrain,

Which PHP version are you using ?

Cheers,
Sander

**Comment by TUBbrain** [comment]
My PHP version is 5.5.37 with all required options and modules on a Apache 2.4.4 :-)

**Comment by TUBbrain** [comment]
If I comment the "bugged" line 29 in myprojectname/vendor/kunstmaan/bundles-cms/src/Kunstmaan/UtilitiesBundle/Helper/Slugifier.php
I can keep on installation.

but another stop at the latest command line : 

-bash-4.1$ bin/console assetic:dump
Dumping all dev assets.
Debug mode is on.

18:47:15 [file+] /home/sites/site199/myprojectname/app/../web/KunstmaanMediaBundleAssets/js/mediaFooter.min.js
[2017-02-21 18:47:15] app.ERROR: RuntimeException: Path to node executable could not be resolved. (uncaught exception) at /home/sites/site199/myprojectname/vendor/kriswallsmith/assetic/src/Assetic/Filter/UglifyJs2Filter.php line 138 while running console command `assetic:dump` {"exception":"[object] (RuntimeException(code: 0): Path to node executable could not be resolved. at /home/sites/site199/myprojectname/vendor/kriswallsmith/assetic/src/Assetic/Filter/UglifyJs2Filter.php:138)"} {"file":"/home/sites/site199/myprojectname/vendor/kunstmaan/bundles-cms/src/Kunstmaan/AdminBundle/EventListener/ConsoleExceptionListener.php","line":28,"class":"Kunstmaan\\AdminBundle\\EventListener\\ConsoleExceptionListener","function":"onConsoleException"}

                                                  
  [RuntimeException]                              
  Path to node executable could not be resolved.

**Comment by sandergo90** [comment]
Do you perhaps don't have the required pecl intl module installed ?

http://php.net/manual/en/transliterator.transliterate.php

The next problem is your config_dev file. You should adapt the node path to the correct location on your machine.

Cheers
