### ISSUE TITLE
Node run build doesn't work

### ISSUE THREAD

**Issue by tperunsky** [Kunstmaan/KunstmaanBundlesStandardEdition#242]
Hello, I'm following the installation guide [here ](https://bundles.kunstmaan.be/documentation/master/installation/intro) and I'm installing the demo app. 
Everything works fine until I get to the `npm run build` step. There is no `build` script defined in package.json and I get this error: https://pastebin.com/Z1g7W8CB
The output of npm install: https://pastebin.com/qQNnkDzY

As a result I can use the admin panel, but not the demo site (js and css are missing, otherwise the raw html loads)
Any help is appreciated.

**Comment by Devolicious** [comment]
Hi @tperunsky,

One of our new features is our new and improved frontend toolset. This is not yet included within a release. You probably started your project from our latest 4.0.2 release. To get the previous frontend toolset working you should follow these instructions: https://bundles.kunstmaan.be/documentation/4.0/installation/intro

Happy coding!
