### ISSUE TITLE
Modal-backdrop doesn't disappear

### ISSUE THREAD

**Issue by anybug** [Kunstmaan/KunstmaanBundlesStandardEdition#256]
Hi,

I use KunstmaanBundle 4.0.2, and when I delete a partpage, the modal-backdrop doesn't disappear...

![screen-backdrop](https://user-images.githubusercontent.com/3168317/37346618-0f50aa06-26d0-11e8-8c7c-b4e445cc31db.jpg)

Does anyone have any idea where this can come from?

**Comment by Devolicious** [comment]
Hi @anybug,

This was an issue with an update of bootstrap. Problem has been solved in the latest 4.1, 4.2 and 5.0 version. So if you update your current project to v4.1.4 you should not have this problem anymore.

**Comment by Devolicious** [comment]
@anybug, also be sure to rerun the `assets:install` and also (if on v4) the `assetic:dump` command.

**Comment by anybug** [comment]
It works
Thank you for your reply
