### ISSUE TITLE
Symfony 2 > CMS Generation

### ISSUE THREAD

**Issue by devswaam** [Kunstmaan/KunstmaanBundlesStandardEdition#76]
Hi All,
          I am new to symfony, while generating is backend, and CMS , some Questions came into my mind. For many of you these can be silly for that i am sorry.

I am looking for a content management system. i did work on sonata admin bundle and got my entity and its CRUD functionality, but when it came to ACL and full permission i couldn't set up that. 
My Question is, is there any difference between this (Kunstman)Bundle) CMS and Sonata admin bundle ? If yes then what ?
In symfony, we just define entity and define an admin class (using sonata , as much i know) we get our CRUD functionality on backend. Does this (Kunstman)bundle provide the same facility ?
Does it freely work with other bundles ? i mean if i use this admin panel can i integrate sonata's E-commerce bundle ?? 

These were some Questions clicked in my mind. If any one can help me. Which one is the best CMS. And the tutorial link please.
Thanks in advance.

**Comment by bobemoe** [comment]
Hi

Yes there are differences between Sonata Admin and the Kunstmaan Admin, as far as I know they use a very different code base, and the admin class is defined slightly differently.  I don't think a Sonata admin class can be used in the Kunstmaan admin, but I've not tried.  However your entities, controllers and 99% of your existing code will work just fine, and it is so easy to generate the admin classes based on your entities that is should be very quick to integrate other bundles/entities into the Kunstmaan Admin.

Which CMS is best is very subjective. Sonata Admin is not a CMS as such, although you can use it to quickly build a basic CMS.  The Symfony CMF is another good framework to build a more complex CMS with, but it is just a framework and needs a lot of work to produce a functional CMS. I like the Kunstmaan Bundles as together they are actually a CMS and very little work needs to be done to get up and running.

Personally if I am building a more database oriented application I prefer the SonataAdmin bundle, however if the application is more focused around content, navigations, translations, media, etc, then I will choose Kunstmaan.
