### ISSUE TITLE
How to add the first page?

### ISSUE THREAD

**Issue by henrypenny** [Kunstmaan/KunstmaanBundlesStandardEdition#84]
It seems with out a homepage there's no means to add a node?

**Comment by sebheitzmann** [comment]
I had the same problem with a fr locale. It's very confusing.

**Comment by denbatte** [comment]
I think this has been fixed when upgrading the generatorBundle in the Kunstmaan CMS 3.1 version.

**Comment by henrypenny** [comment]
I don't think I'll have a chance to check this for a while.
