### ISSUE TITLE
SlugController:slugAction is too big

### ISSUE THREAD

**Issue by guilleferrer** [Kunstmaan/KunstmaanBundlesStandardEdition#86]
80 lines function, with no event Dispatcher. This is the most important function in the KunstmaanBundles and it does too many things. It really needs a refactoring to allow the developers to make use of Events and Services to be overriden.

Not only that, 
"$entity->service($this->container, $request, $renderContext);" 

is really scary. Container should never be injected, if you're doing so, then you should re-think your design.

Please consider refactoring that function and use more services and Events. Allow us to catch hooks and override services.

**Comment by woutervandamme** [comment]
The service method in the entity is now deprecated, you can add logic to your entities by implementing the SlugActionInterface (https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/290), also new events are added to the SlugController (https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/379)
