### ISSUE TITLE
Can't generate default-site with demo data

### ISSUE THREAD

**Issue by reypm** [Kunstmaan/KunstmaanBundlesStandardEdition#94]
I'm following the steps at [docs][1] but this one:

    app/console kuma:generate:default-site --demosite

Is failing with this error:

> Symfony > kuma:generate:default-site --demosite
> Welcome to the Kunstmaan default site generator
> Site generation
> This command helps you to generate a default site setup.
> The layout will be created for the AlomicubaWebsiteBundle bundle.

>   [InvalidArgumentException]
>   Bundle "AlomicubaWebsiteBundle" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your AppKernel.php file?

> kuma:generate:default-site [--namespace[="..."]] [--prefix[="..."]] [--demosite]
> The command terminated with an error status (1)

But bundled is created as this log shows:

> Symfony > kuma:generate:bundle
>   Welcome to the Kunstmaan bundle generator
> ....

> Bundle namespace: Alomicuba/WebsiteBundle
> Bundle name [AlomicubaWebsiteBundle]: WebsiteBundle

> Target directory [/var/www/html/alomicuba/src]:
> Determined 'yml' to be used as the format for the generated configuration

> Summary before generation

> You are going to generate a "Alomicuba\WebsiteBundle\WebsiteBundle" bundle
> in "/var/www/html/alomicuba/src/" using the "yml" format.

> Do you confirm generation [yes]?
>   Bundle generation
> Generating the bundle code: OK
> Checking that the bundle is autoloaded: OK
> Confirm automatic update of your Kernel [yes]?
> Enabling the bundle inside the Kernel: OK
> Confirm automatic update of the Routing [yes]?
> Importing the bundle routing resource: OK

>   You can now start using the generated code!

And also is enabled in `AppKernel.php`, any advice? I'm using the version based on Symfony 2.4

 [1]: http://bundles.kunstmaan.be/getting-started

**Comment by xtrasmal** [comment]
Seems like it is better to use Bolt.cm as a CMS. This one is far from usable. 
Documentation reflects the author's passion and dedication to this bundle.
