### ISSUE TITLE
Postgresql

### ISSUE THREAD

**Issue by totaltrash** [Kunstmaan/KunstmaanBundlesStandardEdition#98]
Hello, i see in the installation documentation that mysql is the preferred database. Unfortunately, I'm locked in to using Postgres. 

During doctrine:schema:create, I'm getting errors due to index names getting used multiple times (for example idx_internal_name is used on NodeBundle\Entity\Node and MediaBundle\Entity\Folder). MySql obviously has no problem with 2 indexes with the same name, but postgres gets upset.

I'm just wondering if the hardcoded names for indexes on these entities are required (doctrine will create a unique hash if the name is not provided)

**Comment by roderik** [comment]
I believe this might be better now since some fixes for sqlite that has the same issue

**Comment by imanzuk** [comment]
Just found that "deleted = 0" where expressions gives "operator does not exist: boolean = integer" error with Postgres. I am going to investigate and fix it with a pull request.
